# Generated by Django 3.2.20 on 2023-08-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acf', models.BigIntegerField()),
                ('asdc', models.BigIntegerField()),
                ('acvvv', models.BigIntegerField()),
                ('avbnsdbf', models.BigIntegerField()),
                ('sdf', models.BigIntegerField()),
            ],
        ),
    ]
